---
title: "P8105_hw1_tj2383"
author: Tanvi Jain
date: 2018-09-15
output: html_document
---

Load necessary packages:

```{r}
library(tidyverse)
```

Set a seed so that results are reproducible:
```{r set_seed}
set.seed(168)
```


Question 1:
```{r question_1_code}
q1_df = tibble(
  random_samp = runif(10, min = 0, max = 5),
  logical_vec = random_samp > 2,
  character_vec = c("dog", "cat", "rabbit", "frog", "mouse", "rat", "fly", "hippo", "horse", "bird"),
  factor_vec = factor(c("low", "medium", "high", "medium", "low", "medium", "high", "low", "low", "high")),
  
mean(random_samp),
mean(logical_vec),
mean(character_vec),
mean(factor_vec),

## The mean can not be computed for the logical, character, and factor variables because the values are not numeric. The mean was calculated for the random sample of uniform distribution.

as.numeric(logical_vec),
as.numeric(character_vec),
as.numeric(factor_vec),

## The as.numeric function converts character values to numeric values. In the logical vector, 0 is FALSE and 1 is TRUE. In the factor vector, 2 is Low, 3 is Medium, and 1 is High. Numeric values cannot be assigned to a character variable.

new_factorvec = as.factor(character_vec),
as.numeric(new_factorvec),
## Since each character variable is unique it created 10 levels when converting to the factor (categorical) variables. Assigned random numbers to the 10 level factor (categorical) variable.

new_charvec = as.character(factor_vec),
as.numeric(new_charvec)

# Converted the factor (categorical) variables to just character variables, as in, did not distinguish the levels. But could not convert from character to nueric because those numeric values cannot be assigned to character variables.

)
```


Question 2:
```{r question_2_code}
q2_df = tibble(
  x = rnorm(1000),
  y = rnorm(1000),
  sum_vec = x + y > 0,
  num_sumvec = as.numeric(sum_vec),
  fac_sumvec = as.factor(num_sumvec)

## The size of the dataset is `r length(fac_sumvec)`. The mean of x is `r mean(x)` and the median of x is `r median(x)`.
)
```





